name: siagakota_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  pdf: ^3.10.4
  printing: ^5.13.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  package_info_plus: ^8.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
